// Generated by the Clawd Strike game repo export flow.
// Do not edit this file in the agent SDK repo; rerun the exporter from the game repo instead.

import {
  PUBLIC_AGENT_CANONICAL_HOST,
  PUBLIC_AGENT_NAME_MAX_LENGTH,
  PUBLIC_AGENT_STABLE_SELECTORS,
  PUBLIC_AGENT_SUPPORTED_GLOBALS,
} from "./contract.mjs";

export const DEFAULT_AGENT_NAME = "SdkAgent";
export const DEFAULT_VIEWPORT = { width: 1440, height: 900 };
export const DEFAULT_RUNTIME_READY_TIMEOUT_MS = 90_000;
export const DEFAULT_FRESH_RUN_TIMEOUT_MS = 20_000;

function safeJsonParse(raw) {
  if (typeof raw !== "string") return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function isRuntimeReadyState(state) {
  return state?.mode === "runtime" && state?.runtimeReady === true;
}

function isFreshRuntimeState(state) {
  return isRuntimeReadyState(state)
    && state?.gameplay?.alive === true
    && state?.gameplay?.gameOverVisible !== true
    && (state?.score?.current ?? null) === 0;
}

export function trimAgentName(value, fallback = DEFAULT_AGENT_NAME) {
  const normalized = typeof value === "string"
    ? value.trim().slice(0, PUBLIC_AGENT_NAME_MAX_LENGTH)
    : String(fallback).trim().slice(0, PUBLIC_AGENT_NAME_MAX_LENGTH);
  return normalized.length > 0 ? normalized : fallback;
}

export function buildRuntimeUrl(baseUrl = PUBLIC_AGENT_CANONICAL_HOST, options = {}) {
  const {
    agentName = DEFAULT_AGENT_NAME,
    autostart = "agent",
    extraSearchParams = {},
  } = options;
  const url = new URL("/", baseUrl);
  url.searchParams.set("autostart", autostart);
  url.searchParams.set("name", trimAgentName(agentName));
  for (const [key, rawValue] of Object.entries(extraSearchParams)) {
    if (rawValue === undefined || rawValue === null || rawValue === false) continue;
    url.searchParams.set(key, String(rawValue));
  }
  return url.toString();
}

export async function launchBrowser(options = {}) {
  const { chromium } = await import("playwright");
  const { headless = true, viewport = DEFAULT_VIEWPORT } = options;
  const browser = await chromium
    .launch({ channel: "chrome", headless })
    .catch(() => chromium.launch({ headless }));
  const context = await browser.newContext({ viewport });
  const page = await context.newPage();
  return { browser, context, page };
}

export async function launchPersistentBrowser(options = {}) {
  const { chromium } = await import("playwright");
  const { userDataDir, headless = true, viewport = DEFAULT_VIEWPORT } = options;
  if (!userDataDir) {
    throw new Error("launchPersistentBrowser requires a userDataDir.");
  }
  const context = await chromium
    .launchPersistentContext(userDataDir, { channel: "chrome", headless, viewport })
    .catch(() => chromium.launchPersistentContext(userDataDir, { headless, viewport }));
  const page = context.pages()[0] ?? await context.newPage();
  return {
    browser: null,
    context,
    page,
  };
}

export function attachConsoleRecorder(page) {
  const events = [];

  const push = (event) => {
    events.push({
      ...event,
      recordedAt: new Date().toISOString(),
    });
  };

  page.on("console", (message) => {
    push({
      kind: "console",
      type: message.type(),
      text: message.text(),
      location: message.location(),
    });
  });

  page.on("pageerror", (error) => {
    push({
      kind: "pageerror",
      type: "error",
      text: error.message,
      stack: error.stack ?? null,
    });
  });

  page.on("requestfailed", (request) => {
    const errorText = request.failure()?.errorText ?? "request failed";
    const aborted = /ERR_ABORTED|NS_BINDING_ABORTED|aborted|cancelled/i.test(errorText);
    push({
      kind: "requestfailed",
      type: aborted ? "warning" : "error",
      text: errorText,
      url: request.url(),
      method: request.method(),
    });
  });

  return {
    clear() {
      events.length = 0;
    },
    snapshot() {
      return events.map((event) => ({ ...event }));
    },
    counts() {
      const errorCount = events.filter((event) => event.type === "error" || event.kind === "pageerror").length;
      const warningCount = events.filter((event) => event.type === "warning" || event.type === "warn").length;
      return {
        errorCount,
        warningCount,
        total: events.length,
      };
    },
  };
}

async function readRawState(page) {
  return page.evaluate(() => {
    if (typeof window.agent_observe === "function") return window.agent_observe();
    if (typeof window.render_game_to_text === "function") return window.render_game_to_text();
    return null;
  });
}

export async function readState(page) {
  const raw = await readRawState(page);
  const state = safeJsonParse(raw);
  if (!state || typeof state !== "object") {
    throw new Error("Documented agent state is unavailable.");
  }
  return state;
}

export async function getAgentApiStatus(page) {
  return page.evaluate((supportedGlobals) => ({
    agentObserve: typeof window.agent_observe === "function",
    renderGameToText: typeof window.render_game_to_text === "function",
    agentApplyAction: typeof window.agent_apply_action === "function",
    advanceTime: typeof window.advanceTime === "function",
    supportedGlobals,
  }), PUBLIC_AGENT_SUPPORTED_GLOBALS);
}

export async function waitForRuntimeReady(page, options = {}) {
  const { timeoutMs = DEFAULT_RUNTIME_READY_TIMEOUT_MS } = options;
  await page.waitForFunction(() => {
    const raw = typeof window.agent_observe === "function"
      ? window.agent_observe()
      : typeof window.render_game_to_text === "function"
        ? window.render_game_to_text()
        : null;
    if (typeof raw !== "string") return false;
    try {
      const state = JSON.parse(raw);
      return state.mode === "runtime" && state.runtimeReady === true;
    } catch {
      return false;
    }
  }, { timeout: timeoutMs });
  return readState(page);
}

export async function clickPlayAgainIfVisible(page) {
  const button = page.locator(PUBLIC_AGENT_STABLE_SELECTORS.playAgain);
  const visible = await button.isVisible().catch(() => false);
  if (!visible) return false;
  await button.click().catch(() => {});
  return true;
}

export async function ensureFreshRun(page, options = {}) {
  const { timeoutMs = DEFAULT_FRESH_RUN_TIMEOUT_MS, pollMs = 150 } = options;
  const deadlineAt = Date.now() + timeoutMs;

  while (Date.now() < deadlineAt) {
    await clickPlayAgainIfVisible(page);
    const state = await readState(page).catch(() => null);
    if (state && isFreshRuntimeState(state)) {
      return state;
    }
    await page.waitForTimeout(pollMs);
  }

  throw new Error(`Timed out waiting for a fresh living run after ${timeoutMs}ms.`);
}

export const waitForRespawn = ensureFreshRun;

export async function gotoAgentRuntimeViaUi(page, options = {}) {
  const { baseUrl = PUBLIC_AGENT_CANONICAL_HOST, agentName = DEFAULT_AGENT_NAME } = options;
  await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
  await page.locator(PUBLIC_AGENT_STABLE_SELECTORS.agentMode).click();
  await page.locator(PUBLIC_AGENT_STABLE_SELECTORS.play).click();
  const agentNameInput = page.locator(PUBLIC_AGENT_STABLE_SELECTORS.agentName);
  await agentNameInput.fill(trimAgentName(agentName));
  await agentNameInput.press("Enter");
  return waitForRuntimeReady(page);
}

export async function gotoAgentRuntimeViaUrl(page, options = {}) {
  const {
    baseUrl = PUBLIC_AGENT_CANONICAL_HOST,
    agentName = DEFAULT_AGENT_NAME,
    extraSearchParams = {},
  } = options;
  await page.goto(buildRuntimeUrl(baseUrl, { agentName, extraSearchParams }), { waitUntil: "domcontentloaded" });
  return waitForRuntimeReady(page);
}

export async function applyAction(page, action) {
  await page.evaluate((nextAction) => {
    window.agent_apply_action?.(nextAction);
  }, action);
}

export async function advance(page, ms = 500) {
  const usedAdvanceTime = await page.evaluate(async (stepMs) => {
    if (typeof window.advanceTime !== "function") return false;
    await window.advanceTime(stepMs);
    return true;
  }, ms);
  if (!usedAdvanceTime) {
    await page.waitForTimeout(ms);
  }
  return usedAdvanceTime;
}

export {
  PUBLIC_AGENT_CANONICAL_HOST,
  PUBLIC_AGENT_NAME_MAX_LENGTH,
  PUBLIC_AGENT_STABLE_SELECTORS,
  PUBLIC_AGENT_SUPPORTED_GLOBALS,
} from "./contract.mjs";
