// Generated by the Clawd Strike game repo export flow.
// Do not edit this file in the agent SDK repo; rerun the exporter from the game repo instead.

export const ADAPTIVE_SWEEPER_POLICY_FAMILY = "adaptive-sweeper";

export const ADAPTIVE_SWEEPER_PARAMETER_SPECS = Object.freeze([
  { key: "strafeWidth", kind: "number", min: 0.05, max: 0.7, step: 0.05, decimals: 2 },
  { key: "strafePeriodTicks", kind: "integer", min: 8, max: 48, step: 2 },
  { key: "sweepAmplitudeDeg", kind: "number", min: 0.2, max: 3.5, step: 0.1, decimals: 2 },
  { key: "sweepPeriodTicks", kind: "integer", min: 8, max: 64, step: 2 },
  { key: "burstLengthTicks", kind: "integer", min: 1, max: 6, step: 1 },
  { key: "burstCooldownTicks", kind: "integer", min: 1, max: 10, step: 1 },
  { key: "reloadThreshold", kind: "integer", min: 1, max: 12, step: 1 },
  { key: "panicTurnDeg", kind: "number", min: 0, max: 20, step: 0.5, decimals: 1 },
  { key: "panicHoldTicks", kind: "integer", min: 0, max: 12, step: 1 },
  { key: "reverseStrafeAfterDamage", kind: "boolean" },
  { key: "crouchEveryTicks", kind: "integer", min: 0, max: 60, step: 2 },
  { key: "crouchHoldTicks", kind: "integer", min: 0, max: 12, step: 1 },
]);

export const DEFAULT_ADAPTIVE_SWEEPER_PARAMETERS = Object.freeze({
  strafeWidth: 0.24,
  strafePeriodTicks: 20,
  sweepAmplitudeDeg: 1.15,
  sweepPeriodTicks: 22,
  burstLengthTicks: 2,
  burstCooldownTicks: 4,
  reloadThreshold: 4,
  panicTurnDeg: 7,
  panicHoldTicks: 3,
  reverseStrafeAfterDamage: true,
  crouchEveryTicks: 0,
  crouchHoldTicks: 0,
});

function clamp(value, min, max) {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

function roundTo(value, decimals = 0) {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}

export function normalizeAdaptiveSweeperParameters(input = {}) {
  const candidate = input && typeof input === "object" ? input : {};
  const normalized = {};
  for (const spec of ADAPTIVE_SWEEPER_PARAMETER_SPECS) {
    const rawValue = candidate[spec.key];
    const fallbackValue = DEFAULT_ADAPTIVE_SWEEPER_PARAMETERS[spec.key];
    if (spec.kind === "boolean") {
      normalized[spec.key] = typeof rawValue === "boolean" ? rawValue : fallbackValue;
      continue;
    }
    const nextValue = typeof rawValue === "number" ? rawValue : fallbackValue;
    const clamped = clamp(nextValue, spec.min, spec.max);
    normalized[spec.key] = spec.kind === "integer"
      ? Math.round(clamped)
      : roundTo(clamped, spec.decimals ?? 2);
  }

  if (normalized.crouchEveryTicks === 0) {
    normalized.crouchHoldTicks = 0;
  } else {
    normalized.crouchHoldTicks = Math.min(normalized.crouchHoldTicks, normalized.crouchEveryTicks);
  }

  return normalized;
}

function emptyAction() {
  return {
    moveX: 0,
    moveZ: 0,
    lookYawDelta: 0,
    fire: false,
    reload: false,
    crouch: false,
  };
}

function findNewestFeedbackEvent(publicState, type) {
  const recentEvents = publicState?.feedback?.recentEvents;
  if (!Array.isArray(recentEvents)) return null;
  for (let index = recentEvents.length - 1; index >= 0; index -= 1) {
    if (recentEvents[index]?.type === type) {
      return recentEvents[index];
    }
  }
  return null;
}

function shouldCrouch(parameters, tickIndex) {
  if (parameters.crouchEveryTicks <= 0 || parameters.crouchHoldTicks <= 0) {
    return false;
  }
  return tickIndex % parameters.crouchEveryTicks < parameters.crouchHoldTicks;
}

export function createAdaptiveSweeperPolicy(policyRecord = {}) {
  const metadata = policyRecord && typeof policyRecord === "object" ? policyRecord : {};
  const parameters = normalizeAdaptiveSweeperParameters(metadata.parameters ?? metadata);
  const family = metadata.family ?? ADAPTIVE_SWEEPER_POLICY_FAMILY;
  const policyId = metadata.policyId ?? `${family}:default`;

  let tickIndex = 0;
  let strafeSign = 1;
  let panicTicksRemaining = 0;
  let lastHandledDamageEventId = 0;
  let burstTicksRemaining = parameters.burstLengthTicks;
  let cooldownTicksRemaining = 0;

  return {
    family,
    policyId,
    parameters,
    reset() {
      tickIndex = 0;
      strafeSign = 1;
      panicTicksRemaining = 0;
      lastHandledDamageEventId = 0;
      burstTicksRemaining = parameters.burstLengthTicks;
      cooldownTicksRemaining = 0;
    },
    nextAction(publicState) {
      if (
        publicState?.mode !== "runtime"
        || publicState?.runtimeReady !== true
        || publicState?.gameplay?.alive !== true
        || publicState?.gameplay?.gameOverVisible === true
      ) {
        return emptyAction();
      }

      const newestDamage = findNewestFeedbackEvent(publicState, "damage-taken");
      if (newestDamage && newestDamage.id > lastHandledDamageEventId) {
        lastHandledDamageEventId = newestDamage.id;
        panicTicksRemaining = parameters.panicHoldTicks;
        if (parameters.reverseStrafeAfterDamage) {
          strafeSign *= -1;
        }
      }

      const strafePhase = (tickIndex % parameters.strafePeriodTicks) / Math.max(1, parameters.strafePeriodTicks);
      const sweepPhase = (tickIndex % parameters.sweepPeriodTicks) / Math.max(1, parameters.sweepPeriodTicks);
      let moveX = Math.sin(strafePhase * Math.PI * 2) * parameters.strafeWidth * strafeSign;
      let lookYawDelta = Math.sin(sweepPhase * Math.PI * 2) * parameters.sweepAmplitudeDeg;

      if (panicTicksRemaining > 0) {
        lookYawDelta += strafeSign * parameters.panicTurnDeg;
        panicTicksRemaining -= 1;
      }

      const ammo = publicState?.ammo ?? null;
      const wantsReload = Boolean(
        ammo
          && ammo.reloading !== true
          && (ammo.mag ?? 0) <= parameters.reloadThreshold
          && (ammo.reserve ?? 0) > 0,
      );

      const action = {
        moveX: clamp(moveX, -1, 1),
        moveZ: 1,
        lookYawDelta: clamp(lookYawDelta, -180, 180),
        fire: false,
        reload: wantsReload,
        crouch: shouldCrouch(parameters, tickIndex),
      };

      if (!wantsReload && ammo?.reloading !== true) {
        if (burstTicksRemaining > 0) {
          action.fire = true;
          burstTicksRemaining -= 1;
          if (burstTicksRemaining === 0) {
            cooldownTicksRemaining = parameters.burstCooldownTicks;
          }
        } else if (cooldownTicksRemaining > 0) {
          cooldownTicksRemaining -= 1;
        } else {
          burstTicksRemaining = parameters.burstLengthTicks;
        }
      }

      tickIndex += 1;
      return action;
    },
  };
}
