import { execFile as execFileCallback } from "node:child_process";
import { createHash } from "node:crypto";
import { access, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import {
  PUBLIC_AGENT_API_VERSION,
  PUBLIC_AGENT_CANONICAL_HOST,
  PUBLIC_AGENT_CANONICAL_SKILLS_URL,
  PUBLIC_AGENT_COMPANION_REPO_NAME,
  PUBLIC_AGENT_COMPANION_REPO_URL,
  PUBLIC_AGENT_CONTRACT,
  PUBLIC_AGENT_NAME_MAX_LENGTH,
  PUBLIC_AGENT_STABLE_SELECTORS,
  PUBLIC_AGENT_SUPPORTED_GLOBALS,
} from "../../apps/shared/publicAgentContract";

const execFile = promisify(execFileCallback);

const EXPORT_MANIFEST_PATH = ".clawd-strike-agent-export.json";
const DEFAULT_TARGET_DIRNAME = PUBLIC_AGENT_COMPANION_REPO_NAME;
const DEFAULT_REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const SOURCE_SKILLS_PATH = "apps/client/public/skills.md";
const CLIENT_PACKAGE_PATH = "apps/client/package.json";
const ROOT_PACKAGE_PATH = "package.json";

type ManagedFile = {
  path: string;
  content: string;
};

type ManagedFileChecksum = {
  path: string;
  sha256: string;
};

type ExistingManifest = {
  managedFiles?: Array<{ path?: unknown }>;
};

export type ExportAgentStarterOptions = {
  outDir?: string;
  dryRun?: boolean;
  expectOrigin?: string;
  repoRoot?: string;
};

export type ExportAgentStarterResult = {
  targetRoot: string;
  dryRun: boolean;
  manifestPath: string;
  managedFiles: ManagedFileChecksum[];
};

function defaultTargetRoot(repoRoot: string): string {
  return path.resolve(repoRoot, "..", DEFAULT_TARGET_DIRNAME);
}

function normalizeRemoteUrl(value: string): string {
  return value.trim().replace(/\.git$/, "");
}

function isPathInside(parentPath: string, childPath: string): boolean {
  const relativePath = path.relative(parentPath, childPath);
  return relativePath !== "" && !relativePath.startsWith("..") && !path.isAbsolute(relativePath);
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJsonFile<T>(filePath: string): Promise<T> {
  return JSON.parse(await readFile(filePath, "utf8")) as T;
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function parsePnpmVersion(packageManager: string | undefined): string {
  if (!packageManager?.startsWith("pnpm@")) {
    return "10";
  }
  return packageManager.slice("pnpm@".length);
}

function renderManagedFileBanner(): string {
  return [
    "Generated by the Clawd Strike game repo export flow.",
    "Do not edit this file in the starter repo; rerun the exporter from the game repo instead.",
  ].join("\n");
}

function renderManagedCodeComment(): string {
  return renderManagedFileBanner()
    .split("\n")
    .map((line) => `// ${line}`)
    .join("\n");
}

function renderSkillsMirror(skillsSource: string): string {
  return [
    "# skills.md - Clawd Strike Agent Contract Mirror",
    "",
    renderManagedFileBanner(),
    `Source of truth: ${PUBLIC_AGENT_CANONICAL_SKILLS_URL}`,
    "",
    "---",
    "",
    skillsSource.trim(),
    "",
  ].join("\n");
}

function renderGitIgnore(): string {
  return [
    "node_modules/",
    "output/",
    "playwright-report/",
    "",
  ].join("\n");
}

function renderPackageJson(playwrightVersion: string, packageManager: string | undefined): string {
  return `${JSON.stringify({
    name: PUBLIC_AGENT_COMPANION_REPO_NAME,
    private: true,
    type: "module",
    packageManager: packageManager ?? "pnpm@10",
    scripts: {
      "smoke:no-context": "node examples/no-context-smoke.mjs",
      "agent:baseline": "node examples/baseline-loop.mjs",
    },
    repository: {
      type: "git",
      url: `${PUBLIC_AGENT_COMPANION_REPO_URL}.git`,
    },
    devDependencies: {
      playwright: playwrightVersion,
    },
  }, null, 2)}\n`;
}

function renderContractModule(): string {
  return [
    renderManagedCodeComment(),
    `export const PUBLIC_AGENT_API_VERSION = ${PUBLIC_AGENT_API_VERSION};`,
    `export const PUBLIC_AGENT_CONTRACT = ${JSON.stringify(PUBLIC_AGENT_CONTRACT)};`,
    `export const PUBLIC_AGENT_CANONICAL_HOST = ${JSON.stringify(PUBLIC_AGENT_CANONICAL_HOST)};`,
    `export const PUBLIC_AGENT_CANONICAL_SKILLS_URL = ${JSON.stringify(PUBLIC_AGENT_CANONICAL_SKILLS_URL)};`,
    `export const PUBLIC_AGENT_COMPANION_REPO_URL = ${JSON.stringify(PUBLIC_AGENT_COMPANION_REPO_URL)};`,
    `export const PUBLIC_AGENT_NAME_MAX_LENGTH = ${PUBLIC_AGENT_NAME_MAX_LENGTH};`,
    `export const PUBLIC_AGENT_STABLE_SELECTORS = Object.freeze(${JSON.stringify(PUBLIC_AGENT_STABLE_SELECTORS, null, 2)});`,
    `export const PUBLIC_AGENT_SUPPORTED_GLOBALS = Object.freeze(${JSON.stringify(PUBLIC_AGENT_SUPPORTED_GLOBALS, null, 2)});`,
    "",
  ].join("\n");
}

function renderIndexModule(): string {
  return [
    renderManagedCodeComment(),
    "import {",
    "  PUBLIC_AGENT_CANONICAL_HOST,",
    "  PUBLIC_AGENT_NAME_MAX_LENGTH,",
    "  PUBLIC_AGENT_STABLE_SELECTORS,",
    "  PUBLIC_AGENT_SUPPORTED_GLOBALS,",
    "} from \"./contract.mjs\";",
    "",
    "export const DEFAULT_AGENT_NAME = \"StarterAgent\";",
    "export const DEFAULT_VIEWPORT = { width: 1440, height: 900 };",
    "",
    "export function trimAgentName(value, fallback = DEFAULT_AGENT_NAME) {",
    "  const normalized = typeof value === \"string\" ? value.trim().slice(0, PUBLIC_AGENT_NAME_MAX_LENGTH) : fallback;",
    "  return normalized.length > 0 ? normalized : fallback;",
    "}",
    "",
    "export function buildRuntimeUrl(baseUrl = PUBLIC_AGENT_CANONICAL_HOST, options = {}) {",
    "  const { agentName = DEFAULT_AGENT_NAME, autostart = \"agent\", extraSearchParams = {} } = options;",
    "  const url = new URL(\"/\", baseUrl);",
    "  url.searchParams.set(\"autostart\", autostart);",
    "  url.searchParams.set(\"name\", trimAgentName(agentName));",
    "  for (const [key, rawValue] of Object.entries(extraSearchParams)) {",
    "    if (rawValue === undefined || rawValue === null || rawValue === false) continue;",
    "    url.searchParams.set(key, String(rawValue));",
    "  }",
    "  return url.toString();",
    "}",
    "",
    "export async function launchBrowser(options = {}) {",
    "  const { chromium } = await import(\"playwright\");",
    "  const { headless = true, viewport = DEFAULT_VIEWPORT } = options;",
    "  const browser = await chromium",
    "    .launch({ channel: \"chrome\", headless })",
    "    .catch(() => chromium.launch({ headless }));",
    "  const context = await browser.newContext({ viewport });",
    "  const page = await context.newPage();",
    "  return { browser, context, page };",
    "}",
    "",
    "export function attachConsoleRecorder(page) {",
    "  const events = [];",
    "  const push = (event) => {",
    "    events.push({ ...event, recordedAt: new Date().toISOString() });",
    "  };",
    "  page.on(\"console\", (message) => {",
    "    push({",
    "      kind: \"console\",",
    "      type: message.type(),",
    "      text: message.text(),",
    "      location: message.location(),",
    "    });",
    "  });",
    "  page.on(\"pageerror\", (error) => {",
    "    push({",
    "      kind: \"pageerror\",",
    "      type: \"error\",",
    "      text: error.message,",
    "      stack: error.stack ?? null,",
    "    });",
    "  });",
    "  return {",
    "    snapshot() {",
    "      return events.map((event) => ({ ...event }));",
    "    },",
    "    counts() {",
    "      const errorCount = events.filter((event) => event.type === \"error\" || event.kind === \"pageerror\").length;",
    "      const warningCount = events.filter((event) => event.type === \"warning\" || event.type === \"warn\").length;",
    "      return { errorCount, warningCount, total: events.length };",
    "    },",
    "  };",
    "}",
    "",
    "export async function readState(page) {",
    "  const state = await page.evaluate(() => {",
    "    const read = () => {",
    "      if (typeof window.agent_observe === \"function\") return window.agent_observe();",
    "      if (typeof window.render_game_to_text === \"function\") return window.render_game_to_text();",
    "      return null;",
    "    };",
    "    const raw = read();",
    "    if (typeof raw !== \"string\") return null;",
    "    try {",
    "      return JSON.parse(raw);",
    "    } catch {",
    "      return null;",
    "    }",
    "  });",
    "  if (!state || typeof state !== \"object\") {",
    "    throw new Error(\"Documented agent state is unavailable.\");",
    "  }",
    "  return state;",
    "}",
    "",
    "export async function getAgentApiStatus(page) {",
    "  return page.evaluate((supportedGlobals) => ({",
    "    agentObserve: typeof window.agent_observe === \"function\",",
    "    renderGameToText: typeof window.render_game_to_text === \"function\",",
    "    agentApplyAction: typeof window.agent_apply_action === \"function\",",
    "    advanceTime: typeof window.advanceTime === \"function\",",
    "    supportedGlobals,",
    "  }), PUBLIC_AGENT_SUPPORTED_GLOBALS);",
    "}",
    "",
    "export async function waitForRuntimeReady(page, options = {}) {",
    "  const { timeoutMs = 90000 } = options;",
    "  await page.waitForFunction(() => {",
    "    const read = () => {",
    "      if (typeof window.agent_observe === \"function\") return window.agent_observe();",
    "      if (typeof window.render_game_to_text === \"function\") return window.render_game_to_text();",
    "      return null;",
    "    };",
    "    const raw = read();",
    "    if (typeof raw !== \"string\") return false;",
    "    try {",
    "      const state = JSON.parse(raw);",
    "      return state.mode === \"runtime\" && state.runtimeReady === true;",
    "    } catch {",
    "      return false;",
    "    }",
    "  }, { timeout: timeoutMs });",
    "  return readState(page);",
    "}",
    "",
    "export async function waitForRespawn(page, options = {}) {",
    "  const { timeoutMs = 20000 } = options;",
    "  await page.waitForFunction(() => {",
    "    const read = () => {",
    "      if (typeof window.agent_observe === \"function\") return window.agent_observe();",
    "      if (typeof window.render_game_to_text === \"function\") return window.render_game_to_text();",
    "      return null;",
    "    };",
    "    const raw = read();",
    "    if (typeof raw !== \"string\") return false;",
    "    try {",
    "      const state = JSON.parse(raw);",
    "      return state.mode === \"runtime\"",
    "        && state.runtimeReady === true",
    "        && state.gameplay?.alive === true",
    "        && state.gameplay?.gameOverVisible !== true;",
    "    } catch {",
    "      return false;",
    "    }",
    "  }, { timeout: timeoutMs });",
    "  return readState(page);",
    "}",
    "",
    "export async function gotoAgentRuntimeViaUi(page, options = {}) {",
    "  const { baseUrl = PUBLIC_AGENT_CANONICAL_HOST, agentName = DEFAULT_AGENT_NAME } = options;",
    "  await page.goto(new URL(\"/\", baseUrl).toString(), { waitUntil: \"domcontentloaded\" });",
    "  await page.locator(PUBLIC_AGENT_STABLE_SELECTORS.agentMode).click();",
    "  await page.locator(PUBLIC_AGENT_STABLE_SELECTORS.play).click();",
    "  const agentNameInput = page.locator(PUBLIC_AGENT_STABLE_SELECTORS.agentName);",
    "  await agentNameInput.fill(trimAgentName(agentName));",
    "  await agentNameInput.press(\"Enter\");",
    "  return waitForRuntimeReady(page);",
    "}",
    "",
    "export async function gotoAgentRuntimeViaUrl(page, options = {}) {",
    "  const { baseUrl = PUBLIC_AGENT_CANONICAL_HOST, agentName = DEFAULT_AGENT_NAME, extraSearchParams = {} } = options;",
    "  await page.goto(buildRuntimeUrl(baseUrl, { agentName, extraSearchParams }), { waitUntil: \"domcontentloaded\" });",
    "  return waitForRuntimeReady(page);",
    "}",
    "",
    "export async function applyAction(page, action) {",
    "  await page.evaluate((nextAction) => {",
    "    window.agent_apply_action?.(nextAction);",
    "  }, action);",
    "}",
    "",
    "export async function advance(page, ms = 500) {",
    "  const usedAdvanceTime = await page.evaluate(async (stepMs) => {",
    "    if (typeof window.advanceTime !== \"function\") return false;",
    "    await window.advanceTime(stepMs);",
    "    return true;",
    "  }, ms);",
    "  if (!usedAdvanceTime) {",
    "    await page.waitForTimeout(ms);",
    "  }",
    "  return usedAdvanceTime;",
    "}",
    "",
    "export async function clickPlayAgainIfVisible(page) {",
    "  const button = page.locator(PUBLIC_AGENT_STABLE_SELECTORS.playAgain);",
    "  const visible = await button.isVisible().catch(() => false);",
    "  if (!visible) return false;",
    "  await button.click().catch(() => {});",
    "  return true;",
    "}",
    "",
    "export {",
    "  PUBLIC_AGENT_CANONICAL_HOST,",
    "  PUBLIC_AGENT_NAME_MAX_LENGTH,",
    "  PUBLIC_AGENT_STABLE_SELECTORS,",
    "  PUBLIC_AGENT_SUPPORTED_GLOBALS,",
    "} from \"./contract.mjs\";",
    "",
  ].join("\n");
}

function renderNoContextSmokeExample(): string {
  return [
    renderManagedCodeComment(),
    "import path from \"node:path\";",
    "import { mkdir, writeFile } from \"node:fs/promises\";",
    "import {",
    "  PUBLIC_AGENT_CANONICAL_HOST,",
    "  advance,",
    "  applyAction,",
    "  attachConsoleRecorder,",
    "  clickPlayAgainIfVisible,",
    "  gotoAgentRuntimeViaUi,",
    "  launchBrowser,",
    "  readState,",
    "  waitForRespawn,",
    "} from \"../src/index.mjs\";",
    "",
    "function timestampId() {",
    "  return new Date().toISOString().replace(/[:.]/g, \"-\");",
    "}",
    "",
    "async function ensureDir(dirPath) {",
    "  await mkdir(dirPath, { recursive: true });",
    "}",
    "",
    "async function writeJson(filePath, payload) {",
    "  await ensureDir(path.dirname(filePath));",
    "  await writeFile(filePath, `${JSON.stringify(payload, null, 2)}\\n`);",
    "}",
    "",
    "const BASE_URL = new URL(process.env.BASE_URL ?? PUBLIC_AGENT_CANONICAL_HOST).toString();",
    "const HEADLESS = process.env.HEADLESS !== \"false\";",
    "const REQUIRED_RESPAWNS = Math.max(1, Number(process.env.REQUIRED_RESPAWNS ?? 1));",
    "const MAX_STEPS = Math.max(1, Number(process.env.MAX_STEPS ?? 120));",
    "const STEP_MS = Math.max(100, Number(process.env.STEP_MS ?? 500));",
    "const OUTPUT_DIR = path.resolve(process.cwd(), process.env.OUTPUT_DIR ?? `output/no-context-smoke/${timestampId()}`);",
    "",
    "await ensureDir(OUTPUT_DIR);",
    "",
    "const { browser, context, page } = await launchBrowser({ headless: HEADLESS });",
    "const consoleRecorder = attachConsoleRecorder(page);",
    "const summary = {",
    "  baseUrl: BASE_URL,",
    "  headless: HEADLESS,",
    "  requiredRespawns: REQUIRED_RESPAWNS,",
    "  maxSteps: MAX_STEPS,",
    "  stepMs: STEP_MS,",
    "  startedAt: new Date().toISOString(),",
    "  runtime: {",
    "    respawnsObserved: 0,",
    "    cycles: [],",
    "  },",
    "};",
    "",
    "try {",
    "  await gotoAgentRuntimeViaUi(page, { baseUrl: BASE_URL, agentName: \"StarterSmoke\" });",
    "  await page.screenshot({ path: path.join(OUTPUT_DIR, \"runtime-start.png\") });",
    "",
    "  let previousAlive = true;",
    "  let completed = false;",
    "",
    "  for (let step = 0; step < MAX_STEPS; step += 1) {",
    "    const state = await readState(page);",
    "    const alive = state.gameplay?.alive === true;",
    "    const gameOverVisible = state.gameplay?.gameOverVisible === true;",
    "",
    "    if (!alive || gameOverVisible) {",
    "      const deathSummary = {",
    "        deathIndex: summary.runtime.cycles.length + 1,",
    "        lastRun: state.score?.lastRun ?? null,",
    "        best: state.score?.best ?? null,",
    "        lastRunSummary: state.lastRunSummary ?? null,",
    "      };",
    "",
    "      if (previousAlive) {",
    "        summary.runtime.cycles.push(deathSummary);",
    "        await page.screenshot({",
    "          path: path.join(OUTPUT_DIR, `death-${deathSummary.deathIndex}.png`),",
    "        });",
    "      }",
    "",
    "      const clicked = await clickPlayAgainIfVisible(page);",
    "      if (!clicked) {",
    "        previousAlive = false;",
    "        await advance(page, STEP_MS);",
    "        continue;",
    "      }",
    "",
    "      const restartedState = await waitForRespawn(page);",
    "      if ((restartedState.score?.current ?? null) !== 0) {",
    "        throw new Error(`Restarted run score should reset to 0, got ${restartedState.score?.current ?? \"n/a\"}`);",
    "      }",
    "",
    "      summary.runtime.respawnsObserved += 1;",
    "      await page.screenshot({",
    "        path: path.join(OUTPUT_DIR, `respawn-${summary.runtime.respawnsObserved}.png`),",
    "      });",
    "",
    "      previousAlive = true;",
    "      if (summary.runtime.respawnsObserved >= REQUIRED_RESPAWNS) {",
    "        completed = true;",
    "        break;",
    "      }",
    "      continue;",
    "    }",
    "",
    "    previousAlive = alive;",
    "    await applyAction(page, {",
    "      moveX: step % 60 < 30 ? 0.25 : -0.2,",
    "      moveZ: 1,",
    "      lookYawDelta: step % 2 === 0 ? 1.35 : -0.7,",
    "      fire: step % 10 === 0,",
    "    });",
    "    await advance(page, STEP_MS);",
    "  }",
    "",
    "  if (!completed) {",
    "    throw new Error(`Observed ${summary.runtime.respawnsObserved} respawns; expected ${REQUIRED_RESPAWNS}.`);",
    "  }",
    "  if (consoleRecorder.counts().errorCount > 0) {",
    "    throw new Error(`Console/page errors observed: ${consoleRecorder.counts().errorCount}`);",
    "  }",
    "",
    "  summary.finishedAt = new Date().toISOString();",
    "  await writeJson(path.join(OUTPUT_DIR, \"summary.json\"), summary);",
    "  await writeJson(path.join(OUTPUT_DIR, \"console.json\"), {",
    "    events: consoleRecorder.snapshot(),",
    "    counts: consoleRecorder.counts(),",
    "  });",
    "  console.log(`[smoke:no-context] pass | respawns=${summary.runtime.respawnsObserved} | output=${OUTPUT_DIR}`);",
    "} catch (error) {",
    "  summary.finishedAt = new Date().toISOString();",
    "  summary.failed = true;",
    "  summary.failure = error instanceof Error ? error.message : String(error);",
    "  await writeJson(path.join(OUTPUT_DIR, \"summary.json\"), summary);",
    "  await writeJson(path.join(OUTPUT_DIR, \"console.json\"), {",
    "    events: consoleRecorder.snapshot(),",
    "    counts: consoleRecorder.counts(),",
    "  });",
    "  throw error;",
    "} finally {",
    "  await context.close();",
    "  await browser.close();",
    "}",
    "",
  ].join("\n");
}

function renderBaselineLoopExample(): string {
  return [
    renderManagedCodeComment(),
    "import {",
    "  PUBLIC_AGENT_CANONICAL_HOST,",
    "  advance,",
    "  applyAction,",
    "  clickPlayAgainIfVisible,",
    "  gotoAgentRuntimeViaUi,",
    "  launchBrowser,",
    "  readState,",
    "  waitForRespawn,",
    "} from \"../src/index.mjs\";",
    "",
    "const BASE_URL = new URL(process.env.BASE_URL ?? PUBLIC_AGENT_CANONICAL_HOST).toString();",
    "const HEADLESS = process.env.HEADLESS !== \"false\";",
    "const MAX_STEPS = Math.max(1, Number(process.env.MAX_STEPS ?? 300));",
    "const STEP_MS = Math.max(100, Number(process.env.STEP_MS ?? 250));",
    "",
    "const { browser, context, page } = await launchBrowser({ headless: HEADLESS });",
    "",
    "try {",
    "  await gotoAgentRuntimeViaUi(page, { baseUrl: BASE_URL, agentName: \"StarterBaseline\" });",
    "",
    "  for (let step = 0; step < MAX_STEPS; step += 1) {",
    "    const state = await readState(page);",
    "    const dead = state.gameplay?.alive === false || state.gameplay?.gameOverVisible === true;",
    "",
    "    if (dead) {",
    "      const clicked = await clickPlayAgainIfVisible(page);",
    "      if (clicked) {",
    "        await waitForRespawn(page);",
    "      } else {",
    "        await advance(page, STEP_MS);",
    "      }",
    "      continue;",
    "    }",
    "",
    "    await applyAction(page, {",
    "      moveX: step % 40 < 20 ? 0.2 : -0.2,",
    "      moveZ: 1,",
    "      lookYawDelta: step % 80 < 40 ? 1.1 : -0.9,",
    "      fire: step % 6 === 0,",
    "      reload: (state.ammo?.mag ?? 0) <= 3,",
    "    });",
    "    await advance(page, STEP_MS);",
    "  }",
    "",
    "  const finalState = await readState(page);",
    "  console.log(JSON.stringify({",
    "    finalScore: finalState.score?.current ?? null,",
    "    best: finalState.score?.best ?? null,",
    "    lastRun: finalState.score?.lastRun ?? null,",
    "  }, null, 2));",
    "} finally {",
    "  await context.close();",
    "  await browser.close();",
    "}",
    "",
  ].join("\n");
}

function renderGitHubWorkflow(pnpmVersion: string): string {
  return [
    "# Generated by the Clawd Strike game repo export flow.",
    "name: Public Agent Smoke",
    "",
    "on:",
    "  workflow_dispatch:",
    "  pull_request:",
    "  push:",
    "    branches:",
    "      - main",
    "",
    "jobs:",
    "  smoke-no-context:",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 20",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: pnpm/action-setup@v4",
    "        with:",
    `          version: ${pnpmVersion}`,
    "      - uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 20",
    "          cache: pnpm",
    "      - run: pnpm install --no-frozen-lockfile",
    "      - run: pnpm exec playwright install --with-deps chromium",
    "      - run: pnpm smoke:no-context",
    "        env:",
    `          BASE_URL: ${PUBLIC_AGENT_CANONICAL_HOST}`,
    "",
  ].join("\n");
}

async function getManagedFiles(repoRoot: string): Promise<ManagedFile[]> {
  const skillsSourcePath = path.join(repoRoot, SOURCE_SKILLS_PATH);
  const clientPackagePath = path.join(repoRoot, CLIENT_PACKAGE_PATH);
  const rootPackagePath = path.join(repoRoot, ROOT_PACKAGE_PATH);
  const skillsSource = await readFile(skillsSourcePath, "utf8");
  const clientPackage = await readJsonFile<{ devDependencies?: Record<string, string> }>(clientPackagePath);
  const rootPackage = await readJsonFile<{ packageManager?: string }>(rootPackagePath);
  const playwrightVersion = clientPackage.devDependencies?.playwright ?? "^1.58.2";
  const packageManager = rootPackage.packageManager;
  const pnpmVersion = parsePnpmVersion(packageManager);

  return [
    { path: "skills.md", content: renderSkillsMirror(skillsSource) },
    { path: ".gitignore", content: renderGitIgnore() },
    { path: "package.json", content: renderPackageJson(playwrightVersion, packageManager) },
    { path: "src/contract.mjs", content: renderContractModule() },
    { path: "src/index.mjs", content: renderIndexModule() },
    { path: "examples/no-context-smoke.mjs", content: renderNoContextSmokeExample() },
    { path: "examples/baseline-loop.mjs", content: renderBaselineLoopExample() },
    { path: ".github/workflows/public-agent-smoke.yml", content: renderGitHubWorkflow(pnpmVersion) },
  ];
}

async function readExistingManagedFiles(targetRoot: string): Promise<string[]> {
  const manifestPath = path.join(targetRoot, EXPORT_MANIFEST_PATH);
  if (!(await pathExists(manifestPath))) {
    return [];
  }

  const manifest = await readJsonFile<ExistingManifest>(manifestPath);
  return Array.isArray(manifest.managedFiles)
    ? manifest.managedFiles
      .map((entry) => (typeof entry.path === "string" ? entry.path : null))
      .filter((entry): entry is string => entry !== null)
    : [];
}

async function readOriginUrl(targetRoot: string): Promise<string | null> {
  try {
    const { stdout } = await execFile("git", ["-C", targetRoot, "config", "--get", "remote.origin.url"]);
    const normalized = stdout.trim();
    return normalized.length > 0 ? normalized : null;
  } catch {
    return null;
  }
}

function assertSafeTarget(repoRoot: string, targetRoot: string): void {
  if (targetRoot === repoRoot) {
    throw new Error("Refusing to export into the game repo itself.");
  }
  if (isPathInside(repoRoot, targetRoot)) {
    throw new Error("Refusing to export into a directory nested inside the game repo.");
  }
}

async function validateTarget(targetRoot: string, expectOrigin?: string): Promise<void> {
  const targetExists = await pathExists(targetRoot);
  if (!targetExists) {
    if (expectOrigin) {
      throw new Error("Cannot validate --expect-origin before the starter repo exists.");
    }
    return;
  }

  const targetStat = await stat(targetRoot);
  if (!targetStat.isDirectory()) {
    throw new Error(`Export target is not a directory: ${targetRoot}`);
  }

  const gitDirPath = path.join(targetRoot, ".git");
  if (!(await pathExists(gitDirPath))) {
    throw new Error("Existing export target must be a separate git repository with a .git directory.");
  }

  if (!expectOrigin) {
    return;
  }

  const originUrl = await readOriginUrl(targetRoot);
  if (!originUrl) {
    throw new Error("Starter repo has no origin remote configured.");
  }
  if (normalizeRemoteUrl(originUrl) !== normalizeRemoteUrl(expectOrigin)) {
    throw new Error(`Starter repo origin mismatch: expected ${expectOrigin}, got ${originUrl}`);
  }
}

async function writeManagedFiles(targetRoot: string, files: ManagedFile[]): Promise<void> {
  for (const file of files) {
    const outputPath = path.join(targetRoot, file.path);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, file.content);
  }
}

async function ensureTargetRepo(targetRoot: string): Promise<void> {
  if (await pathExists(targetRoot)) {
    return;
  }
  await mkdir(targetRoot, { recursive: true });
  await execFile("git", ["init", "--quiet", targetRoot]);
}

async function removeStaleManagedFiles(targetRoot: string, previousManagedFiles: string[], nextManagedFiles: string[]): Promise<void> {
  const nextManagedFileSet = new Set(nextManagedFiles);
  for (const relativePath of previousManagedFiles) {
    if (nextManagedFileSet.has(relativePath)) {
      continue;
    }
    await rm(path.join(targetRoot, relativePath), { force: true });
  }
}

export async function exportAgentStarterRepo(options: ExportAgentStarterOptions = {}): Promise<ExportAgentStarterResult> {
  const repoRoot = path.resolve(options.repoRoot ?? DEFAULT_REPO_ROOT);
  const targetRoot = path.resolve(options.outDir ?? defaultTargetRoot(repoRoot));
  const dryRun = options.dryRun === true;

  assertSafeTarget(repoRoot, targetRoot);
  await validateTarget(targetRoot, options.expectOrigin);

  const files = await getManagedFiles(repoRoot);
  const managedFiles = files
    .map((file) => ({
      path: file.path,
      sha256: sha256(file.content),
    }))
    .sort((left, right) => left.path.localeCompare(right.path));

  const manifest = `${JSON.stringify({
    exportVersion: 1,
    contract: {
      apiVersion: PUBLIC_AGENT_API_VERSION,
      contract: PUBLIC_AGENT_CONTRACT,
      canonicalHost: PUBLIC_AGENT_CANONICAL_HOST,
      canonicalSkillsUrl: PUBLIC_AGENT_CANONICAL_SKILLS_URL,
      companionRepoName: PUBLIC_AGENT_COMPANION_REPO_NAME,
      companionRepoUrl: PUBLIC_AGENT_COMPANION_REPO_URL,
    },
    manifestPath: EXPORT_MANIFEST_PATH,
    managedFiles,
  }, null, 2)}\n`;

  const nextFiles = [
    ...files,
    { path: EXPORT_MANIFEST_PATH, content: manifest },
  ];

  if (!dryRun) {
    await ensureTargetRepo(targetRoot);
    const previousManagedFiles = await readExistingManagedFiles(targetRoot);
    await writeManagedFiles(targetRoot, nextFiles);
    await removeStaleManagedFiles(targetRoot, previousManagedFiles, nextFiles.map((file) => file.path));
  }

  return {
    targetRoot,
    dryRun,
    manifestPath: EXPORT_MANIFEST_PATH,
    managedFiles,
  };
}
