import { execFile as execFileCallback } from "node:child_process";
import { createHash } from "node:crypto";
import { access, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import {
  PUBLIC_AGENT_API_VERSION,
  PUBLIC_AGENT_CANONICAL_HOST,
  PUBLIC_AGENT_CANONICAL_SKILLS_URL,
  PUBLIC_AGENT_COMPANION_REPO_NAME,
  PUBLIC_AGENT_COMPANION_REPO_URL,
  PUBLIC_AGENT_CONTRACT,
  PUBLIC_AGENT_NAME_MAX_LENGTH,
  PUBLIC_AGENT_STABLE_SELECTORS,
  PUBLIC_AGENT_SUPPORTED_GLOBALS,
} from "../../apps/shared/publicAgentContract";

const execFile = promisify(execFileCallback);

const EXPORT_MANIFEST_PATH = ".clawd-strike-agent-export.json";
const DEFAULT_TARGET_DIRNAME = PUBLIC_AGENT_COMPANION_REPO_NAME;
const DEFAULT_REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DEFAULT_TEMPLATE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "agent-sdk-template");
const SOURCE_SKILLS_PATH = "apps/client/public/skills.md";
const CLIENT_PACKAGE_PATH = "apps/client/package.json";
const ROOT_PACKAGE_PATH = "package.json";

type ManagedFile = {
  path: string;
  content: string;
};

type ManagedFileChecksum = {
  path: string;
  sha256: string;
};

type ExistingManifest = {
  managedFiles?: Array<{ path?: unknown }>;
};

export type ExportAgentSdkOptions = {
  outDir?: string;
  dryRun?: boolean;
  expectOrigin?: string;
  repoRoot?: string;
  templateRoot?: string;
};

export type ExportAgentSdkResult = {
  targetRoot: string;
  dryRun: boolean;
  manifestPath: string;
  managedFiles: ManagedFileChecksum[];
};

function defaultTargetRoot(repoRoot: string): string {
  return path.resolve(repoRoot, "..", DEFAULT_TARGET_DIRNAME);
}

function normalizeRemoteUrl(value: string): string {
  return value.trim().replace(/\.git$/, "");
}

function isPathInside(parentPath: string, childPath: string): boolean {
  const relativePath = path.relative(parentPath, childPath);
  return relativePath !== "" && !relativePath.startsWith("..") && !path.isAbsolute(relativePath);
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJsonFile<T>(filePath: string): Promise<T> {
  return JSON.parse(await readFile(filePath, "utf8")) as T;
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function parsePnpmVersion(packageManager: string | undefined): string {
  if (!packageManager?.startsWith("pnpm@")) {
    return "10";
  }
  return packageManager.slice("pnpm@".length);
}

function renderManagedFileBanner(): string {
  return [
    "Generated by the Clawd Strike game repo export flow.",
    "Do not edit this file in the agent SDK repo; rerun the exporter from the game repo instead.",
  ].join("\n");
}

function renderSkillsMirror(skillsSource: string): string {
  return [
    "# skills.md - Clawd Strike Agent Contract Mirror",
    "",
    renderManagedFileBanner(),
    `Source of truth: ${PUBLIC_AGENT_CANONICAL_SKILLS_URL}`,
    "",
    "---",
    "",
    skillsSource.trim(),
    "",
  ].join("\n");
}

async function collectTemplateFiles(rootPath: string, currentPath = rootPath): Promise<ManagedFile[]> {
  const entries = await readdir(currentPath, { withFileTypes: true });
  const files: ManagedFile[] = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const nextPath = path.join(currentPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectTemplateFiles(rootPath, nextPath));
      continue;
    }
    if (!entry.isFile()) {
      continue;
    }
    files.push({
      path: path.relative(rootPath, nextPath).split(path.sep).join("/"),
      content: await readFile(nextPath, "utf8"),
    });
  }
  return files;
}

function renderTemplate(content: string, values: Record<string, string>): string {
  return content.replace(/\{\{([A-Z0-9_]+)\}\}/g, (_match, key: string) => {
    const value = values[key];
    if (value === undefined) {
      throw new Error(`Missing template value for ${key}`);
    }
    return value;
  });
}

async function getManagedFiles(repoRoot: string, templateRoot: string): Promise<ManagedFile[]> {
  const skillsSourcePath = path.join(repoRoot, SOURCE_SKILLS_PATH);
  const clientPackagePath = path.join(repoRoot, CLIENT_PACKAGE_PATH);
  const rootPackagePath = path.join(repoRoot, ROOT_PACKAGE_PATH);
  const skillsSource = await readFile(skillsSourcePath, "utf8");
  const clientPackage = await readJsonFile<{ devDependencies?: Record<string, string> }>(clientPackagePath);
  const rootPackage = await readJsonFile<{ packageManager?: string }>(rootPackagePath);
  const playwrightVersion = clientPackage.devDependencies?.playwright ?? "^1.58.2";
  const packageManager = rootPackage.packageManager ?? "pnpm@10";
  const pnpmVersion = parsePnpmVersion(packageManager);
  const templateValues: Record<string, string> = {
    PACKAGE_MANAGER_JSON: JSON.stringify(packageManager),
    PLAYWRIGHT_VERSION_JSON: JSON.stringify(playwrightVersion),
    PNPM_VERSION: pnpmVersion,
    PUBLIC_AGENT_API_VERSION: String(PUBLIC_AGENT_API_VERSION),
    PUBLIC_AGENT_CANONICAL_HOST: PUBLIC_AGENT_CANONICAL_HOST,
    PUBLIC_AGENT_CANONICAL_HOST_JSON: JSON.stringify(PUBLIC_AGENT_CANONICAL_HOST),
    PUBLIC_AGENT_CANONICAL_SKILLS_URL: PUBLIC_AGENT_CANONICAL_SKILLS_URL,
    PUBLIC_AGENT_CANONICAL_SKILLS_URL_JSON: JSON.stringify(PUBLIC_AGENT_CANONICAL_SKILLS_URL),
    PUBLIC_AGENT_COMPANION_REPO_NAME: PUBLIC_AGENT_COMPANION_REPO_NAME,
    PUBLIC_AGENT_COMPANION_REPO_NAME_JSON: JSON.stringify(PUBLIC_AGENT_COMPANION_REPO_NAME),
    PUBLIC_AGENT_COMPANION_REPO_URL: PUBLIC_AGENT_COMPANION_REPO_URL,
    PUBLIC_AGENT_COMPANION_REPO_URL_GIT_JSON: JSON.stringify(`${PUBLIC_AGENT_COMPANION_REPO_URL}.git`),
    PUBLIC_AGENT_COMPANION_REPO_URL_JSON: JSON.stringify(PUBLIC_AGENT_COMPANION_REPO_URL),
    PUBLIC_AGENT_CONTRACT_JSON: JSON.stringify(PUBLIC_AGENT_CONTRACT),
    PUBLIC_AGENT_NAME_MAX_LENGTH: String(PUBLIC_AGENT_NAME_MAX_LENGTH),
    PUBLIC_AGENT_STABLE_SELECTORS_JSON: JSON.stringify(PUBLIC_AGENT_STABLE_SELECTORS, null, 2),
    PUBLIC_AGENT_SUPPORTED_GLOBALS_JSON: JSON.stringify(PUBLIC_AGENT_SUPPORTED_GLOBALS, null, 2),
  };
  const templateFiles = await collectTemplateFiles(templateRoot);
  const renderedTemplateFiles = templateFiles.map((file) => ({
    path: file.path,
    content: renderTemplate(file.content, templateValues),
  }));

  return [
    { path: "skills.md", content: renderSkillsMirror(skillsSource) },
    ...renderedTemplateFiles,
  ].sort((left, right) => left.path.localeCompare(right.path));
}

async function readExistingManagedFiles(targetRoot: string): Promise<string[]> {
  const manifestPath = path.join(targetRoot, EXPORT_MANIFEST_PATH);
  if (!(await pathExists(manifestPath))) {
    return [];
  }

  const manifest = await readJsonFile<ExistingManifest>(manifestPath);
  return Array.isArray(manifest.managedFiles)
    ? manifest.managedFiles
      .map((entry) => (typeof entry.path === "string" ? entry.path : null))
      .filter((entry): entry is string => entry !== null)
    : [];
}

async function readOriginUrl(targetRoot: string): Promise<string | null> {
  try {
    const { stdout } = await execFile("git", ["-C", targetRoot, "config", "--get", "remote.origin.url"]);
    const normalized = stdout.trim();
    return normalized.length > 0 ? normalized : null;
  } catch {
    return null;
  }
}

function assertSafeTarget(repoRoot: string, targetRoot: string): void {
  if (targetRoot === repoRoot) {
    throw new Error("Refusing to export into the game repo itself.");
  }
  if (isPathInside(repoRoot, targetRoot)) {
    throw new Error("Refusing to export into a directory nested inside the game repo.");
  }
}

async function validateTarget(targetRoot: string, expectOrigin?: string): Promise<void> {
  const targetExists = await pathExists(targetRoot);
  if (!targetExists) {
    if (expectOrigin) {
      throw new Error("Cannot validate --expect-origin before the agent SDK repo exists.");
    }
    return;
  }

  const targetStat = await stat(targetRoot);
  if (!targetStat.isDirectory()) {
    throw new Error(`Export target is not a directory: ${targetRoot}`);
  }

  const gitDirPath = path.join(targetRoot, ".git");
  if (!(await pathExists(gitDirPath))) {
    throw new Error("Existing export target must be a separate git repository with a .git directory.");
  }

  if (!expectOrigin) {
    return;
  }

  const originUrl = await readOriginUrl(targetRoot);
  if (!originUrl) {
    throw new Error("Agent SDK repo has no origin remote configured.");
  }
  if (normalizeRemoteUrl(originUrl) !== normalizeRemoteUrl(expectOrigin)) {
    throw new Error(`Agent SDK repo origin mismatch: expected ${expectOrigin}, got ${originUrl}`);
  }
}

async function writeManagedFiles(targetRoot: string, files: ManagedFile[]): Promise<void> {
  for (const file of files) {
    const outputPath = path.join(targetRoot, file.path);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, file.content);
  }
}

async function ensureTargetRepo(targetRoot: string): Promise<void> {
  if (await pathExists(targetRoot)) {
    return;
  }
  await mkdir(targetRoot, { recursive: true });
  await execFile("git", ["init", "--quiet", targetRoot]);
}

async function removeStaleManagedFiles(targetRoot: string, previousManagedFiles: string[], nextManagedFiles: string[]): Promise<void> {
  const nextManagedFileSet = new Set(nextManagedFiles);
  for (const relativePath of previousManagedFiles) {
    if (nextManagedFileSet.has(relativePath)) {
      continue;
    }
    await rm(path.join(targetRoot, relativePath), { force: true });
  }
}

export async function exportAgentSdkRepo(options: ExportAgentSdkOptions = {}): Promise<ExportAgentSdkResult> {
  const repoRoot = path.resolve(options.repoRoot ?? DEFAULT_REPO_ROOT);
  const targetRoot = path.resolve(options.outDir ?? defaultTargetRoot(repoRoot));
  const dryRun = options.dryRun === true;
  const templateRoot = path.resolve(options.templateRoot ?? DEFAULT_TEMPLATE_ROOT);

  assertSafeTarget(repoRoot, targetRoot);
  await validateTarget(targetRoot, options.expectOrigin);

  const files = await getManagedFiles(repoRoot, templateRoot);
  const managedFiles = files
    .map((file) => ({
      path: file.path,
      sha256: sha256(file.content),
    }))
    .sort((left, right) => left.path.localeCompare(right.path));

  const manifest = `${JSON.stringify({
    exportVersion: 2,
    contract: {
      apiVersion: PUBLIC_AGENT_API_VERSION,
      contract: PUBLIC_AGENT_CONTRACT,
      canonicalHost: PUBLIC_AGENT_CANONICAL_HOST,
      canonicalSkillsUrl: PUBLIC_AGENT_CANONICAL_SKILLS_URL,
      companionRepoName: PUBLIC_AGENT_COMPANION_REPO_NAME,
      companionRepoUrl: PUBLIC_AGENT_COMPANION_REPO_URL,
    },
    manifestPath: EXPORT_MANIFEST_PATH,
    managedFiles,
  }, null, 2)}\n`;

  const nextFiles = [
    ...files,
    { path: EXPORT_MANIFEST_PATH, content: manifest },
  ];

  if (!dryRun) {
    await ensureTargetRepo(targetRoot);
    const previousManagedFiles = await readExistingManagedFiles(targetRoot);
    await writeManagedFiles(targetRoot, nextFiles);
    await removeStaleManagedFiles(targetRoot, previousManagedFiles, nextFiles.map((file) => file.path));
  }

  return {
    targetRoot,
    dryRun,
    manifestPath: EXPORT_MANIFEST_PATH,
    managedFiles,
  };
}
