// Generated by the Clawd Strike game repo export flow.
// Do not edit this file in the agent SDK repo; rerun the exporter from the game repo instead.

import {
  ADAPTIVE_SWEEPER_PARAMETER_SPECS,
  ADAPTIVE_SWEEPER_POLICY_FAMILY,
  normalizeAdaptiveSweeperParameters,
} from "../policies/adaptive-sweeper.mjs";

function hashSeed(input) {
  const text = String(input);
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

export function createSeededRng(seed) {
  let state = hashSeed(seed) || 1;
  return {
    seed: state,
    next() {
      state = (state + 0x6d2b79f5) >>> 0;
      let t = Math.imul(state ^ (state >>> 15), 1 | state);
      t ^= t + Math.imul(t ^ (t >>> 7), 61 | t);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    },
    nextInt(min, max) {
      if (max <= min) return min;
      return min + Math.floor(this.next() * (max - min + 1));
    },
    pick(items) {
      return items[this.nextInt(0, items.length - 1)];
    },
  };
}

function mean(values) {
  if (values.length === 0) return 0;
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function median(values) {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((left, right) => left - right);
  const middle = Math.floor(sorted.length / 2);
  if (sorted.length % 2 === 1) {
    return sorted[middle];
  }
  return (sorted[middle - 1] + sorted[middle]) / 2;
}

export function aggregateBatchMetrics(episodes) {
  const completedEpisodes = episodes.filter((episode) => episode.completed !== false);
  const scores = completedEpisodes.map((episode) => Number(episode.finalScore ?? 0));
  const survivalTimes = completedEpisodes.map((episode) => Number(episode.survivalTimeS ?? 0));
  const accuracies = completedEpisodes.map((episode) => Number(episode.accuracy ?? 0));
  const shotsFired = completedEpisodes.map((episode) => Number(episode.shotsFired ?? 0));
  const totalKills = completedEpisodes.reduce((sum, episode) => sum + Number(episode.kills ?? 0), 0);
  const killPositiveEpisodes = completedEpisodes.filter((episode) => Number(episode.kills ?? 0) > 0).length;

  return {
    episodeCount: episodes.length,
    completedEpisodes: completedEpisodes.length,
    killPositiveEpisodes,
    totalKills,
    bestScore: scores.length > 0 ? Math.max(...scores) : 0,
    medianScore: median(scores),
    meanScore: mean(scores),
    meanSurvivalTime: mean(survivalTimes),
    meanAccuracy: mean(accuracies),
    meanShotsFired: mean(shotsFired),
  };
}

export function meetsBootstrapGate(metrics, options = {}) {
  const { batchSize = 5, minKillPositiveEpisodes = 1 } = options;
  return metrics.completedEpisodes >= batchSize && metrics.killPositiveEpisodes >= minKillPositiveEpisodes;
}

function isAccuracyComparable(candidateMetrics, championMetrics) {
  const baseline = Math.max(1, Number(championMetrics.meanShotsFired ?? 0));
  return Math.abs(Number(candidateMetrics.meanShotsFired ?? 0) - Number(championMetrics.meanShotsFired ?? 0)) <= baseline * 0.2;
}

export function compareBatchMetrics(candidateMetrics, championMetrics) {
  const comparisons = [
    ["killPositiveEpisodes", Number(candidateMetrics.killPositiveEpisodes ?? 0), Number(championMetrics.killPositiveEpisodes ?? 0)],
    ["totalKills", Number(candidateMetrics.totalKills ?? 0), Number(championMetrics.totalKills ?? 0)],
    ["bestScore", Number(candidateMetrics.bestScore ?? 0), Number(championMetrics.bestScore ?? 0)],
    ["medianScore", Number(candidateMetrics.medianScore ?? 0), Number(championMetrics.medianScore ?? 0)],
    ["meanScore", Number(candidateMetrics.meanScore ?? 0), Number(championMetrics.meanScore ?? 0)],
    ["meanSurvivalTime", Number(candidateMetrics.meanSurvivalTime ?? 0), Number(championMetrics.meanSurvivalTime ?? 0)],
  ];

  for (const [metric, candidateValue, championValue] of comparisons) {
    if (candidateValue === championValue) continue;
    return {
      order: candidateValue > championValue ? 1 : -1,
      decisiveMetric: metric,
      comparableAccuracy: isAccuracyComparable(candidateMetrics, championMetrics),
    };
  }

  if (isAccuracyComparable(candidateMetrics, championMetrics)) {
    const candidateAccuracy = Number(candidateMetrics.meanAccuracy ?? 0);
    const championAccuracy = Number(championMetrics.meanAccuracy ?? 0);
    if (candidateAccuracy !== championAccuracy) {
      return {
        order: candidateAccuracy > championAccuracy ? 1 : -1,
        decisiveMetric: "meanAccuracy",
        comparableAccuracy: true,
      };
    }
  }

  return {
    order: 0,
    decisiveMetric: "tie",
    comparableAccuracy: isAccuracyComparable(candidateMetrics, championMetrics),
  };
}

function clampParameterValue(spec, value) {
  if (spec.kind === "boolean") {
    return Boolean(value);
  }
  const clamped = Math.min(spec.max, Math.max(spec.min, value));
  if (spec.kind === "integer") {
    return Math.round(clamped);
  }
  const decimals = spec.decimals ?? 2;
  const factor = 10 ** decimals;
  return Math.round(clamped * factor) / factor;
}

function chooseMutationSpecs(focus) {
  const preferredKeys = focus === "bootstrap"
    ? new Set(["strafeWidth", "sweepAmplitudeDeg", "burstCooldownTicks", "reloadThreshold", "panicTurnDeg", "reverseStrafeAfterDamage"])
    : new Set();
  const prioritized = [];
  const remaining = [];
  for (const spec of ADAPTIVE_SWEEPER_PARAMETER_SPECS) {
    if (preferredKeys.has(spec.key)) {
      prioritized.push(spec);
    } else {
      remaining.push(spec);
    }
  }
  return [...prioritized, ...remaining];
}

export function createCandidatePolicyRecord(options) {
  const {
    championPolicy,
    hallOfFame = [],
    generation,
    seed,
    focus = "bootstrap",
  } = options;

  const rng = createSeededRng(`${seed}:${generation}:${championPolicy?.policyId ?? "baseline"}`);
  const parentPool = [championPolicy, ...hallOfFame].filter(Boolean);
  const parentPolicy = parentPool.length > 1 && rng.next() < 0.25
    ? parentPool[rng.nextInt(0, parentPool.length - 1)]
    : championPolicy;

  const baseParameters = normalizeAdaptiveSweeperParameters(parentPolicy?.parameters ?? {});
  const parameterSpecs = chooseMutationSpecs(focus);
  const mutationCount = rng.next() < 0.5 ? 1 : 2;
  const usedKeys = new Set();
  const mutationSummary = [];
  const nextParameters = { ...baseParameters };

  while (mutationSummary.length < mutationCount) {
    const spec = rng.pick(parameterSpecs.filter((entry) => !usedKeys.has(entry.key)));
    if (!spec) break;
    usedKeys.add(spec.key);
    const previousValue = nextParameters[spec.key];
    let nextValue = previousValue;

    if (spec.kind === "boolean") {
      nextValue = !previousValue;
    } else {
      const deltaDirection = rng.next() < 0.5 ? -1 : 1;
      const stepMultiplier = spec.kind === "integer" ? rng.nextInt(1, 2) : rng.nextInt(1, 3);
      nextValue = clampParameterValue(spec, previousValue + (spec.step * stepMultiplier * deltaDirection));
      if (nextValue === previousValue) {
        nextValue = clampParameterValue(spec, previousValue - (spec.step * stepMultiplier * deltaDirection));
      }
    }

    nextParameters[spec.key] = nextValue;
    mutationSummary.push({
      key: spec.key,
      previousValue,
      nextValue,
    });
  }

  const normalizedParameters = normalizeAdaptiveSweeperParameters(nextParameters);
  const seedHash = hashSeed(`${seed}:${generation}`).toString(16).padStart(8, "0");

  return {
    family: ADAPTIVE_SWEEPER_POLICY_FAMILY,
    policyId: `${ADAPTIVE_SWEEPER_POLICY_FAMILY}-g${String(generation).padStart(4, "0")}-${seedHash}`,
    parentPolicyId: parentPolicy?.policyId ?? null,
    generation,
    seed: hashSeed(seed),
    focus,
    parameters: normalizedParameters,
    mutationSummary,
  };
}

export function updateHallOfFame(existingEntries, nextEntry, maxEntries = 5) {
  const deduped = [...existingEntries.filter((entry) => entry.policyId !== nextEntry.policyId), nextEntry];
  deduped.sort((left, right) => compareBatchMetrics(right.metrics, left.metrics).order);
  return deduped.slice(0, maxEntries);
}
