// Generated by the Clawd Strike game repo export flow.
// Do not edit this file in the agent SDK repo; rerun the exporter from the game repo instead.

import path from "node:path";
import { access, appendFile, mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";

export async function ensureDir(dirPath) {
  await mkdir(dirPath, { recursive: true });
}

export async function pathExists(targetPath) {
  try {
    await access(targetPath);
    return true;
  } catch {
    return false;
  }
}

export function resolveStatePaths(rootDir) {
  const resolvedRoot = path.resolve(rootDir);
  const candidateSummariesDir = path.join(resolvedRoot, "candidate-summaries");
  const browserProfileDir = path.join(resolvedRoot, "browser-profile");
  return {
    rootDir: resolvedRoot,
    browserProfileDir,
    episodesPath: path.join(resolvedRoot, "episodes.jsonl"),
    championPolicyPath: path.join(resolvedRoot, "champion-policy.json"),
    semanticMemoryPath: path.join(resolvedRoot, "semantic-memory.json"),
    hallOfFamePath: path.join(resolvedRoot, "hall-of-fame.json"),
    latestSessionSummaryPath: path.join(resolvedRoot, "latest-session-summary.json"),
    candidateSummariesDir,
  };
}

export async function readJson(filePath, fallback = null) {
  try {
    return JSON.parse(await readFile(filePath, "utf8"));
  } catch {
    return fallback;
  }
}

export async function readJsonLines(filePath) {
  try {
    const raw = await readFile(filePath, "utf8");
    return raw
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .map((line) => JSON.parse(line));
  } catch {
    return [];
  }
}

export async function appendJsonLine(filePath, payload) {
  await ensureDir(path.dirname(filePath));
  await appendFile(filePath, `${JSON.stringify(payload)}\n`);
}

export async function writeJsonAtomic(filePath, payload) {
  await ensureDir(path.dirname(filePath));
  const tempPath = `${filePath}.tmp-${process.pid}`;
  await writeFile(tempPath, `${JSON.stringify(payload, null, 2)}\n`);
  await rename(tempPath, filePath);
}

export async function appendEpisode(paths, payload) {
  await appendJsonLine(paths.episodesPath, payload);
}

export async function writeChampionPolicy(paths, payload) {
  await writeJsonAtomic(paths.championPolicyPath, payload);
}

export async function writeSemanticMemory(paths, payload) {
  await writeJsonAtomic(paths.semanticMemoryPath, payload);
}

export async function writeHallOfFame(paths, payload) {
  await writeJsonAtomic(paths.hallOfFamePath, payload);
}

export async function writeLatestSessionSummary(paths, payload) {
  await writeJsonAtomic(paths.latestSessionSummaryPath, payload);
}

export async function writeCandidateSummary(paths, candidateId, payload) {
  await ensureDir(paths.candidateSummariesDir);
  const filePath = path.join(paths.candidateSummariesDir, `${candidateId}.json`);
  await writeJsonAtomic(filePath, payload);
  return filePath;
}

export async function listCandidateSummaries(paths) {
  if (!(await pathExists(paths.candidateSummariesDir))) {
    return [];
  }
  const entries = await readdir(paths.candidateSummariesDir, { withFileTypes: true });
  const summaries = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
    const filePath = path.join(paths.candidateSummariesDir, entry.name);
    const payload = await readJson(filePath, null);
    if (payload) {
      summaries.push(payload);
    }
  }
  return summaries;
}
